### ISSUE TITLE
Question: How to filter type:music ?

### ISSUE THREAD

**Issue by MehmetAliKOCAL** [TimeForANinja/node-ytsr#199]
I'm using node-ytsr in my youtube music clone app like this:

const ytsr = require("ytsr");

const filters1 = await ytsr.getFilters("unfazed");
const filter1 = filters1.get("Type").get("Music");
const options = {
  limit: 1,
};
const searchResults = await ytsr(filter1.url, options);

But I get an error "500: Cannot read properties of undefined (reading 'url')"

When I search for types Video and Playlist, everything is fine. Aren't there type filters for songs or albums?

**Comment by ttrreevvoorr** [comment]
I don't see a filter option for `Music` on YouTube, only `Video`, `Channel`, `Playlist`, and `Movie`. 
Is there existing functionality you're trying to reproduce? 

![image](https://github.com/TimeForANinja/node-ytsr/assets/53444861/a0b0e7b3-0b2e-4ca7-a1a1-8879562a74a4)

If it helps, I've been adding "audio" to my search terms to try and find music instead of music _videos_ when searching for tracks. But if you know something about YouTube filtering that I haven't seen yet please share :D
