### ISSUE TITLE
Limit question

### ISSUE THREAD

**Issue by vasyl-shumskyi** [TimeForANinja/node-ytsr#26]
Can you please explain how `limit` works?

If we put some insane number like 1,000 or so - will the module break this number on smaller chunks and parse youtube by pages automatically? 

Is there any possibility that youtube will rate-limit such big numbers on its side? Or there is some prevention mechanism in `ystr` like timeouts between queries or so?  

Thanks in advance.

**Comment by TimeForANinja** [comment]
Exactly, youtube does only return a limited amount of items with each search. When you need more than those the library automatically retrieves the "get more" link from the bottom and does another fetch, until there is no "get more" button or we reached the user set limit.

There is a high chance that youtube does ratelimiting (stumbled into those using fent/node-ytdl-core myself) but those are pretty high. A plus point is that we don't pull to much data in parallel, since we need the "get more" ref from the previous page.

There currently is no implementation of any timeout/q since i haven't heard of any way to retrieve the limits.

**Comment by vasyl-shumskyi** [comment]
Perfectness! Thanks, @TimeForANinja
